#!/bin/bash

person1=Ramesh
person2=Suresh

echo "$person1:: Hi ${person2}, How are you?"
echo "${person2}:: Hello $person1 I am fine. How are you doing?"
echo "$person1:: I am doing good ${person2}. What's going on?"
echo "${person2}:: I started learning Shell Script $person1"